### PR TITLE
Troll armor set nerf: First attempt™️

### PR DESCRIPTION
**Pull request by SenatorSupreme**
https://discord.com/channels/620840315498004480/714540497171120199/815726720400883733

### CODE REVIEW

**Comment by democat3457** [comment]
bro
you dont have to make a new pull request

**Comment by democat3457** [comment]
new commits to the branch are counted in the pull request

**Comment by SenatorSupreme** [comment]
OH. shit.

**Comment by democat3457** [comment]
And also you can close pull requests

**Pull request merged**
