### PR TITLE
Troll armor set bonus nerf

### PR DESCRIPTION
**Pull request by SenatorSupreme**
https://discord.com/channels/620840315498004480/714540497171120199/815726720400883733

### CODE REVIEW

**Comment by democat3457** [comment]
silly rat, you also have to change the potion down in the effects section

**Comment by SenatorSupreme** [comment]
Fug. how do you do that

**Comment by democat3457** [comment]
ctrl-f for the set bonus id

**Comment by democat3457** [comment]
#686

**Pull request closed without merging**
