### PR TITLE
Crafting sounds

### PR DESCRIPTION
**Pull request by juraj-hrivnak**
Adds configurable crafting sounds using the PlayerCraftedEvent, and updates CraftTweaker and ZenUtils.
You can easily add new crafting sounds just by adding new entries to the maps, like:
```ZenScript
val itemsAndSounds as string[IItemStack] = {
    <contenttweaker:broken_stick>   : "minecraft:block.wood.break",
    ...,
    ...
};
```
And then run `/ct reload` to reload it in-game.

### CODE REVIEW

**Comment by Foreck1** [comment]
Because we didn't merge this soon enough, there are a few conflicts now. I will manually add the changes and close the pull request when that is done.

**Comment by juraj-hrivnak** [comment]
I reverted the commit that updated CraftTweaker & ZenUtils, so this can be merged now.

**Comment by democat3457** [comment]
@Foreck1 do we want this on master or stable (or both)

**Comment by juraj-hrivnak** [comment]
Yes, it does. By default it adds sounds for:
```zenscript
<contenttweaker:broken_stick>

<ore:rock>
<ore:stickWood>
<ore:workbench>

IMaterial.iron()
IMaterial.rock()
IMaterial.wood()
IMaterial.ground()
IMaterial.cloth()
IMaterial.glass()
IMaterial.piston()
```

**Comment by Foreck1** [comment]
> @Foreck1 do we want this on master or stable (or both)

I say both still.

**Comment by democat3457** [comment]
aight

**Pull request merged**
