### PR TITLE
add simple gradle build

### PR DESCRIPTION
**Pull request by SekretOne**
Adding a simple (if gradle can be) build with simple clean / copyMods tasks. Testing can be reliably done from the target directory, and not risk introducing unwanted changes or artifacts.

The introduction of a build process will also allow for some tools to make configuration easier and safer- as well as some automated testing. One step at a time.

## edit:

for clarification, what this grants is a gradle build that takes the source files and puts them into a output folder using `copyMods`

```
rebirth-of-the-night
     mods
        ...all them jars
     config
     ambience_music
    MOTD.txt
    ... etc
```

and copies them to 

```
rebirth-of-the-night
    build
        target
            + mods
            + ...all them jars
            + config
            + ambience_music
            + MOTD.txt
            + ... etc
```

the `clean` operation wipes.

The advantage is you can now reliably test the output without introducing accidental changes or artifacts to the source, or having to duplicate the whole source folder by hand.

It's also a necessary step to having a task creates a publishable zip for the client and server pack. Remove the human work from the process and automate it. Make it faster, and more reliable.

### CODE REVIEW

**Comment by democat3457** [comment]
i dont *think* we need gradle for anything, especially building stuff. I'm assuming your intention is to have changes on a separate instance than the dev repository, but putting the generated files into the gitignore works just as effectively.

**Comment by democat3457** [comment]
also this branch has the changes from chore/idea, making #702 obsolete

**Comment by SekretOne** [comment]
> I'm assuming your intention is to have changes on a separate instance than the dev repository, but putting the generated files into the gitignore works just as effectively.

I'm not following what you're saying here. "changes on a separate instance than the dev repository?"

The intention is to change the repo to the source, rather than the output. A little odd since right now all the 'build' is, is copying all the stuff to a `build/target` so if you run / test locally you don't muddy the source files.

>  but putting the generated files into the gitignore works just as effectively.

Yes, that's what it does. Before . . . there was no generation  . . .

**Comment by democat3457** [comment]
I'm not sure I'm getting what you're saying here either tbh...

**Comment by SekretOne** [comment]
> I'm not sure I'm getting what you're saying here either tbh...
> What do you mean by source files?

So for something simple you might just version control the file or files as is. For a more complex thing, especially one with a lot of moving parts, you split it out.

1. `source` the 'raw' code or pieces, and instructions on how to put it together, and even tests
2. `build` the runnable thing that gets put together after running the 'build' instructions
3. `distribution`, the final artifact(s), like a minimized zip. Sort of the build code all polished up and ready to passed around to users. Say, put it all together and generate the curseForge manifest, etc.

The source would be version controlled. If you want to test, you'd build and run that. If all looks good to ship, run the distribution command and package the thing up for you. And just as importantly, it does it consistently.

A build doesn't *have* to be code compilation. It could be that, or it could be as basic as zipping it together for  you and putting the right version number. Or all matter of inbetween.

What we have here is it being treated like both source and build/distribution (not exactly, as I'm sure @CalaMariGold has some extra steps that need to be done to get it dist ready). The result is a bit of play where you poop. In my experience that results in a fair amount of bugs.

**Comment by democat3457** [comment]
hm. well, i know mari uses the curseforge launcher to export the pack, so I'm not sure that can be entirely automated - and the build/ folder would be pretty much identical to the repo as it is now, since the curseforge launcher needs to be used to export the zip in order for it to count properly for the site upload

**Comment by SekretOne** [comment]
Yes- it's very limited what it's doing now, since I don't want to change anything on how people can *currently* do things.

First step is to allow the option for something safer. Now you can test locally by running the gradle build and spinning up your MC on the build directory, and not the base directory source.

**Comment by democat3457** [comment]
wait so run the git repo from `build/..`, and run minecraft from `build/.`?

**Comment by SekretOne** [comment]
I'm not entirely sure what you mean by 'running the git repo'.  I think I just need to see what it is you're doing- there's some assumption being made.

Steps would be as follows:

1. check out repo (you've already done this so no reason to do it again)
2. run `gradlew copyMods`
3. a few seconds later you'll see a `./build/target` dir that's untracked that's basically the same contents
4. if you test, test off the `./build/target` and not the root
5. use the `gradlew  clean` command to wipe that directory and build again with `gradlew copyMods`

**Comment by democat3457** [comment]
so then what if the game generates configs or something like that? how would gradle transfer stuff back from build/target to the git repo

**Comment by SekretOne** [comment]
> so then what if the game generates configs or something like that? how would gradle transfer stuff back from build/target to the git repo

You don't. That's kind of the point. 

1. If it's derivative you don't need to. If the game was just going to generate it the way you wanted it to ... you don't need to commit it.
2. If it's an overridden config, you deliberately add that to your source.

**Comment by democat3457** [comment]
Doesn't it seem overly redundant then? To rather instead of selectively committing generated files and using the .gitignore, use a build process that may still require you to copy around files, as well as deal with the added trouble of forgetting to use `copyMods` to update your build directory?

**Comment by SekretOne** [comment]
> Doesn't it seem overly redundant then? 

No. A .gitignore doesn't selectively commit, but selectively ignore.

Look, the best I can summarise this is: consider why anything like maven or gradle exists. *Compilers already existed.* What do those thing try to solve for?

It is possible to have a script driven release process for the modpack. However, it is impossible without some kind of build process.

**Comment by kil0byt3** [comment]
https://github.com/NillerMedDild/ModpackUploader

**Comment by democat3457** [comment]
idk i just dont think the modpack needs a script driven release - iirc even mari declined to use the modpackuploader link that was sent by kilo, when it was brought up in dev chat

**Comment by CalaMariGold** [comment]
I've already discussed this with sekret privately. I do want this.

**Comment by kil0byt3** [comment]
Oh, good to know we've changed our mind

**Comment by democat3457** [comment]
i guess its ok then :|

**Pull request merged**
