### PR TITLE
Radiant Crystal Tooltip

### PR DESCRIPTION
**Pull request by SenatorSupreme**

### CODE REVIEW

**Comment by democat3457** [comment]
why are changes on your master branch

**Comment by democat3457** [comment]
@SenatorSupreme not going to merge until extraneous commits are removed

**Comment by SenatorSupreme** [comment]
Oh yeah i forgot about this, give me like 30 minutes

**Comment by InlustrisXIII** [comment]
Idk about the arcanearchives.zs change, but shouldn't the tweaked atlas position be added? Would keep the atlas from covering the day counter. @democat3457

**Comment by SenatorSupreme** [comment]
No I've already committed those
I fucked up and did everything in one place, so there's duplicates. There should only really be the change to arcane archives.

**Comment by InlustrisXIII** [comment]
ah okay, my apologies. Nice tho

**Pull request closed without merging**
