### PR TITLE
Modify values for various foods

### PR DESCRIPTION
**Pull request by SylvanasIII**
Increased food values of surf and turf, vegemite on toast, and cheese vegemite toast decreased food value of vegemite.

### CODE REVIEW

**Comment by SylvanasIII** [comment]
I'll be modifying this with other foods as I go.

**Comment by SylvanasIII** [comment]
If anyone has any foods they know that need adjusted, feel free to mention them here so I know what to modify next.

**Comment by KaleThyself** [comment]
Can non-Pam's HC foods be adjusted in food.zs?

**Comment by SylvanasIII** [comment]
Yep. Some already have, like wolf chops and roasted R A T.

**Comment by SylvanasIII** [comment]
Also, to clarify what the unnamed changes were, beet burger was nerfed and nether star toast was massively buffed.

**Comment by KaleThyself** [comment]
Had some free time today...

1. Nearly all of the base fruits/vegetables/grains that Pam's HC provides restore half a hunger bar and half a saturation bar. However, cantaloupe is the only basic crop that restores one full hunger bar per piece. 
2. Various food recipes that require toast need fixing.
3. Cup of tea, nor bubble tea (don't hate me) should arguably not restore any hunger since a cup of coffee does not restore hunger. 
4. Sesame seeds can be toasted, but the toasted sesame seeds can't be eaten or crafted into anything such as being added to a plain burger. Personally, I recommend adding toasted sesame seeds to the recipe for making a burger since the current burger recipe is patty + bread in a kettle. 
5. The eye pie recipe is still able to be crafted/viewed in JEI when looking at what dough can be crafted into.
6. Silken tofu is able to be pressed into soy milk/firm tofu, allowing players to craft the bottle of milk which removes all potion effects (just like a vanilla bucket of milk). 
7. Change fried egg hunger restoration from half a hunger bar into one hunger bar as to not create discrepancies. 
8. Change the scrambled egg recipe to be more realistic instead of using the lazy recipe of 3 eggs in a kettle. 
9. Change the recipe for egg salad into requiring a boiled egg, mayo, and/or potatoes instead of a raw egg and mayo. 
10. Most soups that require stock are redundant in hunger values. 
11. While spaghetti has a recipe, spaghetti and meatballs has no recipe. 
12. Pork lettuce wrap restores the same amount of hunger/saturation as fish lettuce wrap. Pork lettuce wrap should restore more saturation than fish lettuce wrap as pork generally has a higher fat content. 
13. Corn on the cob shows three cobs in the dish, but only requires one ear of corn in the recipe. (yes, of course I'm going to nitpick that) 
14. Peanut butter and banana sandwiches restore one and a half hunger bars while PB&J sandwiches restore three and a half hunger bars. Other nut butter and jelly sandwiches besides honey sandwiches restore four hunger bars. 
15. The chocolate bar restores one hunger bar, but chili chocolate which requires batter and a chili still restores one hunger bar. 
16. Lemonade only uses lemons and water...eugh. (I like adding honey to my lemonade) 
17. The chocolate cherry requires one chocolate and one pair of cherries, but only a singular chocolate cherry is shown as the output. 
18. Raspberry iced tea, sweet tea, green tea, marigold tea, rose petal tea, espresso, coffee con leche, and "tea, early gray, hot" restores half a hunger bar. (See `3.` for reference) 
19. Zucchini fries restore one and a half more hunger bars than zucchini bread. As someone who has had zucchini bread before, it is way more filling than fries. 
20. Pam's shellfish and other non-fish type meats are currently unobtainable. I don't know the future plans for them, but for now the recipes such as these should be removed:
 - coconut shrimp
 - cooked oyster/oyster sauce
 - cantonese greens
 - cooked clam
 - cooked crab
 - cooked crayfish
 - cooked frog legs
 - cooked scallop
 - cooked shrimp
 - cooked snail
 - cooked turtle
 - cooked mussel
 - crayfish salad
 - jellied eel
 - shrimp tempura
 - crawfish etoufee
21. In the same way beet burgers were nerfed, hearty breakfast should probably be nerfed. 
22. Maple sausage is a useless half hunger restoring food. (buff required)
23. Honeycomb chocolate bar restores two and a half hunger bars for no reason whatsoever. 
24. Fairy bread restores only one hunger bar. 
25. Chocolate bacon restores three and a half hunger bars and five and a half saturation bars. (needs nerf)
26. Nutella by itself can't be crafted into anything, but it restores two and a half hunger bars. 
27. Pepperonis by themselves restore four hunger bars and four saturation bars. A whole fricken pizza restores the same exact amount. 
28. Milkshakes only restore one hunger bar while smoothies restore one and a half hunger bars. 
29. Naan doesn't have a recipe it can craft into. 
30. Paneer tikka masala only restores two hunger bars. (buff required)
31. Hot and sour soup may need a buff due to how many ingredients are used in the dish. 
32. Peking duck vs Char Siu; both use five spice, but only char siu has massive hunger restoration. Peking duck only has two hunger bars restoration. 
33. Apple fritter restores three and a half hunger bars. (nerf required) 
34. Perhaps the creeper cookie should be buffed as it requires a charged creeper chunk now. 
35. Meatloaf by itself stores four and a half hunger bars while a meatloaf sandwich restores only three hunger bars. 
36. Nether wings seem a tad bit too weak despite the blaze powder requirement to craft them. 
37. Guacamole currently has no recipe it crafts into, so matching it with tortilla chips would be logical. Since chips and salsa is a dish in pam's hc already. 
38. Cookies and milk only restore half a hunger bar. (buff required)
39. Crackers restore two hunger bars and one saturation bar while crackers and cheese restore two hunger bars and one and a half saturation bars. (buff required due to how tough cheese is to get) 
40. Chicken dinner only restores two and a half hunger bars. (buff required)
41. Ham and cheese sandwich only restores 2 hunger bars. (buff required)
42. A butter cookie is less fulfilling than a sugar cookie. (buff to butter cookie required) 
43. Chips and dip restores less hunger than bbq potato chips. 
44. Tater tots are less fulfilling than mashed potatoes despite using more than the same ingredients. 
45. Smores have the same hunger restoration and saturation as steak fajitas. Go figure. 
46. Crispy rice puff cereal restores only half a hunger bar. (buff required)
47. Tomato herb chicken only restores one hunger bar. (buff required)
48. Ducks don't exist in RoTN, so it's impossible to acquire any duck besides ~~tofuck~~ _ahem_ I mean **tofuduck.** Either way, cooked duck/tofuduck restore only half a hunger bar instead of one full hunger bar like other cooked meats. 
49. Ham and pineapple pizza restores only two and a half hunger bars. (buff required)
50. Mettbrötchen only restores two hunger bars despite using expensive ingredients. (buff required)
51. An egg tar restores more hunger and saturation than an egg roll. 
52. Steak tartare only restores one and a half hunger bars. (buff required)
53. Bacon pancakes only restore one and a half hunger bars. (buff required)
54. I would like to personally request kale chips to be buffed from half a hunger bar to at least one hunger bar. 
55. Since slime gummies require 1 raw venison, they should restore more than half a hunger bar. 
56. BBQ chicken pizza only restores two and a half hunger bars. (buff required)
57. BBQ jackfruit cannot be obtained. 
58. Lychee tea cannot be crafted. 
59. Chicken cordon bleu restores only two hunger bars. 
60. The chocolate bar restores one hunger bar while the chocolate coconut bar restores half a hunger bar. 
61. Gyudon restores only one and a half hunger bar. (buff required)
62. Fried bologna sandwich only restores two hunger bars. (buff required)
63. A normal bologna sandwich restores two and a half hunger bars. (buff required?)
64. Imitation crab sticks restore more hunger than a musubi. 
65. Schnitzel has no recipe. 
66. Cooked tofu alternatives to meat restore absurd amounts of hunger compared to normal cooked meat (not prime). 
67. Lamb kebab restores four and a half hunger bars while sauced lamb kebab restores only two and a half hunger bars. (buff required)
68. "Sweet pickle and ham sandwich" restores only two and a half hunger bars despite being a full sandwich. (buff required)
69. Glistening salad is still in RoTN. 
70. Bratwurst has no recipe. 
71. Epic BLT has no recipe. 
72. [non-pam's hc] congealed magma cream is unobtainable. 
73. [non-pam's hc] Cooked rice from growthcraft currently has no use and only restores half a hunger bar. 
74. [non-pam's hc] Growthcraft ice creams restore only half a hunger bar. I don't see a recipe for them either. 
75. [non-pam's hc] Betteranimalsplus crab meat isn't obtainable as the only crabs that spawn are quark's horseshoe crabs and normal quark crabs. 
76. [non-pam's hc] Cooked venison restores two hunger bars while prime cooked meats restore only one and a half hunger bars. 

This is all I bothered doing, but there could be more discrepancies that I missed.

**Comment by kil0byt3** [comment]
> This is **all** I bothered doing

Fuckin right bud, you’ve done more than enough. Thanks so much for compiling all that. We’ll have a looksie

**Comment by SylvanasIII** [comment]
...dear gods that's a lot. I'm gonna stick with adjusting hunger values and leave the addition/removal of recipes to someone else for now.

**Comment by SylvanasIII** [comment]
It is DONE! All of the changes I plan on doing for this list have been completed! Not everything is done, but that's because all I did was alter hunger values. Warning that I don't have the best understanding of saturation values, so they might be off.

**Comment by KaleThyself** [comment]
> It is DONE! All of the changes I plan on doing for this list have been completed! Not everything is done, but that's because all I did was alter hunger values. Warning that I don't have the best understanding of saturation values, so they might be off.

Rule of thumb I usually see is that saturation values are 1.5-3 bars lower than the hunger restoration values. However, it strongly depends on the food type. For example, ice cream or another sugary treat will generally have a lower saturation value than something like pasta with meatballs or a meatloaf sandwich.

**Comment by SylvanasIII** [comment]
That wouldn't be an issue if it was just adding a number of bars. Problem is, saturation is a modifier, not a flat number. I think 0.5 makes the saturation equal to the total bars, judging by the values already present in the file, so I based my numbers off that.

**Comment by SandwichHorror** [comment]
I like it. I approve. Ready to test these changes in the next beta, another huge step in food rebalancing.

**Review by SandwichHorror — APPROVED** [review]
I wrote the review in the other comment. My bad

**Review by kil0byt3 — APPROVED** [review]
LG2M 👍🏻

**Review by democat3457 — APPROVED** [review]

**Comment by Landsurfer2000** [comment]
jesus this is beautiful

**Review by Landsurfer2000 — APPROVED** [review]

**Comment by kil0byt3** [comment]
Reviews are in and this looks good, thanks for your work. G2M, merging

**Pull request merged**
