### PR TITLE
Make zombies attack plague doctors

### PR DESCRIPTION
**Pull request by democat3457**
Also attack toroquest entities like shopkeeper, guards, sentries
Applies same behavior to zombie villagers

### CODE REVIEW

**Comment by SandwichHorror** [comment]
Thank you. will save for 2.79 when villages are better. As it is, grunts are infinite, but also very dumb and the villages WILL be completely gone in one night. At least some guards and doctors remain after that... to make villages feel slightly more populated beyond infinite grunts

**Comment by democat3457** [comment]
Aight lmao

**Comment by SandwichHorror** [comment]
This is somewhat inconclusive without the other zombie variants. Do you think it's worth adding all zombie variants: Fishing, Fire, Hungry, Plague plus the "advanced variants" like Frigid and Overgrown to this list?

My concern would be that with so many additional monsters having automatic aggro against guards, the villages genuinely have no chance to survive. Or perhaps this is intended, that the monsters the player has unleashed through their actions have consequences, and any village must be fortified by the player to survive into lategame?

**Comment by CalaMariGold** [comment]
Closing due to inactivity

**Comment by democat3457** [comment]
It does say "planned fix" and 
> will save for 4.0 when villages are better

**Comment by democat3457** [comment]
But I marked it as draft since it's technically "in progress."

**Pull request closed without merging**
