### PR TITLE
Add AA textures

### PR DESCRIPTION
**Pull request by democat3457**
It does have colors, though, which might interfere with AA's existing textures.

### CODE REVIEW

**Comment by democat3457** [comment]
Also I can't enable the resource pack by default without removing options.txt from the .gitignore, so y'all are going to have to enable the resource pack manually.

**Comment by CalaMariGold** [comment]
@democat3457 are you gonna merge this?

**Comment by democat3457** [comment]
I wasn't sure whether you wanted colored textures (the vanilla textures would also have to be colored to match).

**Comment by democat3457** [comment]
Actually the pack already has colored textures for vanilla biomes, no problemo.

**Pull request merged**
