### PR TITLE
horsepoewer fixes

### PR DESCRIPTION
**Pull request by DokMephisto**
updated entity ids to correct ids used in game for horse powered items

### CODE REVIEW

**Comment by democat3457** [comment]
Is zombie horse supposed to be removed?

**Comment by DokMephisto** [comment]
I can revert that, but Zombie Horses can't be leashed

**Comment by democat3457** [comment]
I see, it should be fine then

**Comment by democat3457** [comment]
Can you change the branch from master to stable though

**Comment by democat3457** [comment]
Shoot that did not like that

**Comment by DokMephisto** [comment]
Did it change?

**Comment by democat3457** [comment]
It did change, but it really doesn't like it

**Pull request closed without merging**
